%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

%global __cmake_in_source_build 1

Name:           ros-kilted-ouster-ros
Version:        0.13.15
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS ouster_ros package

License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       curl
Requires:       jsoncpp
Requires:       libcurl-devel
Requires:       libtins-devel
Requires:       ros-kilted-cv-bridge
Requires:       ros-kilted-geometry-msgs
Requires:       ros-kilted-launch
Requires:       ros-kilted-launch-ros
Requires:       ros-kilted-ouster-sensor-msgs
Requires:       ros-kilted-pcl-conversions
Requires:       ros-kilted-pcl-ros
Requires:       ros-kilted-rclcpp
Requires:       ros-kilted-rclcpp-components
Requires:       ros-kilted-rclcpp-lifecycle
Requires:       ros-kilted-rosidl-default-runtime
Requires:       ros-kilted-sensor-msgs
Requires:       ros-kilted-std-msgs
Requires:       ros-kilted-std-srvs
Requires:       ros-kilted-tf2-ros
Requires:       spdlog-devel
Requires:       ros-kilted-ros-workspace
BuildRequires:  curl
BuildRequires:  eigen3-devel
BuildRequires:  jsoncpp-devel
BuildRequires:  libcurl-devel
BuildRequires:  libtins-devel
BuildRequires:  pcl-devel
BuildRequires:  ros-kilted-ament-cmake
BuildRequires:  ros-kilted-cv-bridge
BuildRequires:  ros-kilted-geometry-msgs
BuildRequires:  ros-kilted-ouster-sensor-msgs
BuildRequires:  ros-kilted-pcl-conversions
BuildRequires:  ros-kilted-pcl-ros
BuildRequires:  ros-kilted-rclcpp
BuildRequires:  ros-kilted-rclcpp-components
BuildRequires:  ros-kilted-rclcpp-lifecycle
BuildRequires:  ros-kilted-rosidl-default-generators
BuildRequires:  ros-kilted-sensor-msgs
BuildRequires:  ros-kilted-std-msgs
BuildRequires:  ros-kilted-std-srvs
BuildRequires:  ros-kilted-tf2-eigen
BuildRequires:  ros-kilted-tf2-ros
BuildRequires:  spdlog-devel
BuildRequires:  ros-kilted-ros-workspace
BuildRequires:  ros-kilted-rosidl-typesupport-fastrtps-c
BuildRequires:  ros-kilted-rosidl-typesupport-fastrtps-cpp
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}
Provides:       ros-kilted-rosidl-interface-packages(member)

%if 0%{?with_tests}
BuildRequires:  gtest-devel
%endif

%if 0%{?with_weak_deps}
Supplements:    ros-kilted-rosidl-interface-packages(all)
%endif

%description
Ouster ROS2 driver

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DAMENT_PREFIX_PATH="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
%license LICENSE
/opt/ros/kilted

%changelog
* Tue Oct 28 2025 ouster developers <oss@ouster.io> - 0.13.15-1
- Autogenerated by Bloom

* Tue Apr 22 2025 Ussama Naal <ussama.naal@ouster.io> - 0.11.1-6
- Autogenerated by Bloom

* Wed Mar 06 2024 Ussama Naal <ussama.naal@ouster.io> - 0.11.1-5
- Autogenerated by Bloom

